export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const UPDATE_DAILY_CAL = "UPDATE_DAILY_CAL";
export const FETCH_EXERCISE_TABLE = "FETCH_EXERCISE_TABLE";
